import { AIService } from '../services/aiService';
import { PromptTemplates } from '../services/promptTemplates';

export class PrismaGenerator {
  static async generateSchema(description: string): Promise<string> {
    try {
      const prompt = PromptTemplates.prismaSchema(description);
      const schema = await AIService.callAI(prompt, { task: 'text-generation' });
      if (schema && schema.includes('model')) return schema;
    } catch (e) {
      // fallback ниже
    }
    // Fallback: простая схема User/Post
    return `
// Auto-generated by AutoDevStack
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  posts Post[]
}

model Post {
  id      Int    @id @default(autoincrement())
  title   String
  content String?
  userId  Int
  user    User   @relation(fields: [userId], references: [id])
}
`;
  }
} 